### ISSUE TITLE
contextutils: sharing logger with child context

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/go-utils#201]
when getting a child context and cancel function, it would be nice to share the parent's logger with the child

```go
// instead of this
childCtxWithNoLogger, cancel := context.WithCancel(parentCtxThatAlreadyHasALogger)
// now calling contextutils.LoggerFrom(...) produces a new logger

// we could support this this
childCtxWithParentLogger, cancel := contextutils.WithCancelInheritLogger(parentCtxThatAlreadyHasALogger)
// now calling contextutils.LoggerFrom(...) uses the parent logger
// could also add a field that would log a reference to the parent logger
```

I think this would be useful, leaving a note about it here for feedback and so I don't forget

**Comment by ilackarms** [comment]
does `context.WithCancel` not inherit all the properties of the parent context?

**Comment by mitchdraft** [comment]
I think so but I haven't had a chance to test.
Since writing, I found that another issue was causing the logging error that inspired this issue/question.
This can be closed if stale or when verified

**Comment by rickducott** [comment]
Going to close as stale, we can reopen if we need to but doesn’t sound like there’s reason to believe there’s an issue here anymore
