### ISSUE TITLE
Unknown / Ambiguous License information

### ISSUE THREAD

**Issue by warthog9** [solo-io/go-utils#210]
The project, currently, doesn't seem to have any known license information pertaining to it. There's no /LICENSE file, and none of the core files have any header indications on what copyright / license the files are actually under. There's pieces that do indicate license information for the piece, https://github.com/solo-io/solo-kit/blame/master/test/mocks/api/doc/google/rpc/status.proto.sk.md#L13, for example but overall I'm not seeing anything or solo-kit itself.

Can some clarification be made as to the actual license of the code?

**Comment by rickducott** [comment]
Sorry about that, I am adding an Apache 2.0 license in #218

**Comment by rickducott** [comment]
Fixed in #218
