### ISSUE TITLE
Security scan opens issues for releases without vulnerabilities

### ISSUE THREAD

**Issue by bewebi** [solo-io/go-utils#532]
# Overview
Security alert issues, such as solo-io/gloo#10039, are being opened for releases that do not have any vulnerabilities according to the scans
This causes confusion, as the opening of Security Alert issues implies that vulnerabilities are present and need to be addressed, and simply closing them is not a sustainable workaround since a new issue will be reopened the next time the scan runs

## Cause

This appears to be due to a change from #525 whereby we now _always_ populate `vulnerabilityMd`, adding a message that explicitly states that no vulnerabilities were found for each image for which no vulnerabilities were found

This breaks an assumption made [here](https://github.com/solo-io/go-utils/blob/be2cbfc162b271a47e2ecf22637e79535208fb5b/securityscanutils/issuewriter/github_writer.go#L85) in `GithubIssueWriter.Write()` that if there are no vulnerabilities, the argument passed as `vulnerabilityMarkdown` will be empty

## Further Investigation

We (Gateway team) should check in with Platform team to learn about their Trivy Issue usage and whether/why they're OK with Github issues always being opened

## Solution

`SecurityScanRepo.RunMarkdownScan()` currently always calls `GithubIssueWriter.Write()` and relies on that function to determine whether an issue should be written, however since the original code was written, the issue-writing became one implementation of an `IssueWriter` interface rather than a stand-alone function

The `LocalIssueWriter` implementation of `Write()` does not attempt to determine whether an issue should be written, and the description of `Write()` in the interface definition does not allude to this being part of the function's responsibility

Therefore we should determine whether an issue should be written prior to calling `Write()` (ie within `SecurityScanRep.RunMarkdownScan()`) and remove code from `GithubIssueWriter.Write()` that attempts to determine whether an issue should be written

**Comment by sam-heilbron** [comment]
Nice find! In the end, this issue creation is purely a tactic used internally to notify engineers of work that needs to be tackled, and doesn't have an impact on what is published in our user-facing docs, correct?

If that is the case, since we know _why_ this is occurring, I would be ok just leaving it as is, and basically err on the side of over-creating issues, even if there is nothing to be done. 

@nfuden @bewebi any concerns with that?

**Comment by bewebi** [comment]
The process for generating the Gloo Gateway docs page with CVE reporting is a bit convoluted and not well documented, but effectively isolated from the opening of issues

To summarize:
- The docs-gen workflow, which runs on push to LTS branches, among other times, invokes the `build-site` make target [here](https://github.com/solo-io/gloo/blob/8079fff2da2ee9ec64e0c3ad051b4abef667c108/.github/workflows/docs-gen.yaml#L108)
- `build-site` invokes `build-docs.sh` [here](https://github.com/solo-io/gloo/blob/f7c3d64192ba607dc77e7d6453a6a1f819756fae/docs/Makefile#L87), which in turn invokes the `site-release` target [here](https://github.com/solo-io/gloo/blob/e590e4274db86ac350c633237d20b32b83874747/docs/build-docs.sh#L389), which has `site-common` as a prerequisite
- `site-common` generates security scan Markdown [here](https://github.com/solo-io/gloo/blob/f7c3d64192ba607dc77e7d6453a6a1f819756fae/docs/Makefile#L31-L32) for both OSS and EE, sending output from each to a file in the `content/static/content` directory
  - This output consists of scan results in Markdown format for every release on an LTS branch since the [`MIN_SCANNED_VERSION`](https://github.com/solo-io/gloo/blob/f7c3d64192ba607dc77e7d6453a6a1f819756fae/docs/Makefile#L14)
  - The `gen-security-scan-md` command, defined [here](https://github.com/solo-io/gloo/blob/ca379296e08f29684b918a887b97130b439ec309/docs/cmd/generate_docs.go#L73) is invoked, and generates output by retrieving files for each scanned image from a GCloud bucket [here](https://github.com/solo-io/gloo/blob/063dbf3ba7b7666d0111741c083b197364b14716/docs/cmd/securityscanutils/securityscan_utils.go#L104)
  - Those files are created when a security scan is run by [these lines](https://github.com/solo-io/go-utils/blob/8eda16b9878d71673e6a3a9756f6088160f75468/securityscanutils/securityscan.go#L263-L) in go-utils code
  - In the case of Gloo Gateway, these scans are run weekly on Monday mornings as part of [this Github action](https://github.com/solo-io/gloo/blob/87f2db78463e60e93be8337af87649bf36c79be8/.github/workflows/trivy-analysis-scheduled.yaml), with the scans run via the `run-security-scan` target and the generated files are subsequently uploaded to Google storage via the `publish-security-scan` target
- `site-common` then splits the Markdown files into separate files for each release [here](https://github.com/solo-io/gloo/blob/f7c3d64192ba607dc77e7d6453a6a1f819756fae/docs/Makefile#L34-L35)
- These files populate the security update docs pages by reference [here](https://github.com/solo-io/gloo/blob/9452148fd727e6ba8da1457721ec4487d495200b/docs/content/reference/security-updates/open_source/_index.md?plain=1#L9-L12) and [here](https://github.com/solo-io/gloo/blob/9452148fd727e6ba8da1457721ec4487d495200b/docs/content/reference/security-updates/enterprise/_index.md?plain=1#L9-L12)

This summary should probably be in a README of some sort in the Gateway OSS repo, but leaving it here for the moment

As far as whether to actually act on this issue, I would still be in favor, as it's confusing to have Security Alert issues when there are no vulnerabilities with potentially serious ramifications
If we have a practice of checking all of the issues every Monday we shouldn't miss anything, but we can no longer rely on the existence of an issue to indicate that there are vulnerabilities to resolve
This is confusing, especially for outside observers who might wonder why there are so many Security Alert issues, and as a team we may not always be on top of actually opening them to check that they're empty since they're _usually_ false alarms
It would be much better to return to the previous behavior whereby an issue was only opened when a vulnerability was found and action was required

Before doing so, we should check in with Platform to make sure that resolving this bug would not break any of their workflows and, if it would, we should collaborate on a solution that works for both teams
