### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by rickducott** [solo-io/go-utils#87]
* A standard log library should be provided that can initialize a logger from the context (something already exists in `contextutils/context_and_logging.go`)
* The log library should abstract away the implementation (i.e. Zap) so we could swap to a different library (i.e. zerolog) if we wanted to in the future
* Need to be able to log messages at different levels (TRACE, DEBUG, INFO, WARN, ERROR, FATAL)
* Need to be able to configure log settings in a standard way for services and CLIs. The configuration should allow specifying: 
  * A global log level (i.e. INFO), such that messages below this level (i.e. DEBUG) don't get logged
  * a strategy for rolling over logs (i.e. after they get to a certain size, or after a certain date) compress and start a new log); deleting log archives after some retention period
  * (Future) a customizable output format (to start, having a standard format across all things is good)
* CLI loggers should output to the local output directory (i.e. HOME/.gloo)

Once this is done, we should update all our projects:
* Get rid of `fmt.Print` except in CLIs that deliberately are printing user-facing output
* Use correct loggers everywhere

**Comment by marcogschmidt** [comment]
How about a being able to define multiple loggers, each with its own output and level? I am thinking CLI specifically, where we might want to log only INFO and above to console, but might still want DEBUG to go to a file?

**Comment by rickducott** [comment]
Multiple loggers could work, but I'm used to stdout being used as the formatted / user-facing channel, and loggers being used for diagnostics. We don't want log-formatted messages being written to the console when executing CLIs

**Comment by rickducott** [comment]
Discussed, it could be implemented just as well in a log library. And then we could also validate we never commit fmt.Print statements

**Comment by yuval-k** [comment]
- as for configuration, i would also want it be dynamically configurable from the admin page (like we have it today)
- and the structured feature is very nice - i.e. you can log keys and values and not just a message
- as for log roll over, usually kubernetes takes care of that - why do we need to worry about it? if we install in vms we can leverage logrotate command.

**Comment by rickducott** [comment]
Also concerned about CLI log bloat in the local home directory, but that is unlikely to be a problem for a very long time so I'd be happy punting on that for now

**Comment by ilackarms** [comment]
the "12 factor way" of handling logging is to simply use stderr/stdout and let the infra tooling handle storage / exposing the logs

according to https://12factor.net/logs:
> A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout.

this is the assumption that kubernetes (and other container platforms) makes when dealing with logs for the user

**Comment by rickducott** [comment]
Our use case diverges somewhat in that the CLI is not a saas / 12-factor app. That said, I'm all in favor of letting Kube handle the routing / management and the underlying logger writer may end up just being stdout

**Comment by rickducott** [comment]
Think this is done with @joekelley and @mitchdraft 's work
